### ISSUE TITLE
Menu Issue Causing Short Pages to be too Long

### ISSUE THREAD

**Issue by newseed** [dynamicdriverepo/ddsmoothmenu#5]
This is something I never experience before and I know it's because of the menu that has multiple levels.

Look at this page:
http://www.euroasiaimports.com/productcartv51/pc/viewCategories.asp

Now scroll down to the bottom and you will see a lot of space below the footer. This is caused by that menu.  How can I overcome this?

**Comment by dynamicdriverepo** [comment]
Ok, I've identified and resolved the bug in the latest version of ddsmoothmenu.js (v3.01). At the moment you can grab the file on the script's homepage: http://www.dynamicdrive.com/dynamicindex1/ddsmoothmenu.htm I'll be updating the repo shortly with the update as well.
